add 172. Factorial Trailing Zeroes
nayuta-ai/Leetcode pull request #26
Opened 2021-08-31 10:11 UTC by nayuta-ai

2021-08-31 11:27 UTC, tkkawa requested changes

2021-08-31 11:27 UTC, tkkawa commented on 172_Factorial_Trailing_Zeroes.py
> +            cnt = cnt + n//(5**i)
cnt += n // (5 ** i)

2021-08-31 11:27 UTC, tkkawa commented on 172_Factorial_Trailing_Zeroes.py
> +                break;
insert a blank line after break statement

2021-09-01 00:35 UTC, nayuta-ai commented on 172_Factorial_Trailing_Zeroes.py
> +            cnt = cnt + n//(5**i)
- insert space

2021-09-01 00:35 UTC, nayuta-ai commented on 172_Factorial_Trailing_Zeroes.py
> +                break;
- insert a blank

2021-09-05 02:51 UTC, tkkawa requested changes

2021-09-05 02:51 UTC, tkkawa commented on 172_Factorial_Trailing_Zeroes.py
> +            cnt = cnt + n // (5 ** i)
cnt += n // (5 ** i)

2021-09-24 12:55 UTC, tkkawa approved these changes
LGTM

2021-10-03 03:52 UTC, merged