add 141. Linked List Cycle
nayuta-ai/Leetcode pull request #8
Opened 2021-08-13 03:21 UTC by nayuta-ai

2021-08-15 14:33 UTC, tkkawa requested changes
write time and space complexity

2021-08-15 14:33 UTC, tkkawa commented on 141_Linked_List_Cycle.py
> +                return True
Leave one line after "return"

2021-08-15 14:33 UTC, tkkawa commented on 141_Linked_List_Cycle.py
> +            if fast==slow:
Insert a space before and after ==

2021-08-22 14:01 UTC, nayuta-ai commented on 141_Linked_List_Cycle.py
> +                return True
leave this line

2021-08-22 14:01 UTC, nayuta-ai commented on 141_Linked_List_Cycle.py
> +            if fast==slow:
Insert a space in line 14

2021-08-31 11:29 UTC, tkkawa requested changes
write both time complexity and space complexity

2021-09-05 02:41 UTC, tkkawa requested changes

2021-09-05 02:41 UTC, tkkawa commented on 141_Linked_List_Cycle.py
> +# space O(n)
O(1)

2021-09-24 12:46 UTC, tkkawa approved these changes
LGTM

2021-10-03 03:44 UTC, merged